sudo: required
services:
  - docker
before_install : 
  - gem install bundler --pre
  - docker build -t arbaazkhan03/react -f Dockerfile.dev .   

script:
  - docker run arbaazkhan03/react npm run test -- --coverage
  